development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: bitreturn_dev
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: bitreturn_test
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: bitreturn
  username: root
  password:
